language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

      # Test the latest stable release
    - php: 7.1
    - php: 7.2
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - composer run test